version: '3.8'
name: nexusmanager-feature

services:
  # --- 3. BACKEND API PRINCIPAL (TYPESCRIPT) ---
  # --- 3. BACKEND API PRINCIPAL (TYPESCRIPT) ---
  backend-ft:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: gestion_backend_ts-ft
    restart: always
    ports:
      - "8002:8000"
    environment:
      - SQL_SERVER_URL=mssql://sa:${SQL_SA_PASSWORD}@sqlserver-pd:1433/gestion_db
      - MONGO_URL=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb-pd:27017/
      - UPLOAD_DIR=/app/uploads
      - PYTHON_SERVICE_URL=http://excel-processor-ft:8001
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./data/uploads:/app/uploads
      - ./prisma:/app/prisma
    networks:
      - default
      - nexus-network

  # --- 4. PROCESADOR DE EXCEL (PYTHON) ---
  excel-processor-ft:
    build:
      context: .
      dockerfile: excel-processor/Dockerfile
    container_name: gestion_python_worker-ft
    restart: always
    ports:
      - "8003:8001"
    environment:
      - SQL_SERVER_URL=mssql+pyodbc://sa:${SQL_SA_PASSWORD}@sqlserver-pd:1433/gestion_db?driver=ODBC+Driver+18+for+SQL+Server
      - MONGO_URL=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb-pd:27017/
      - UPLOAD_DIR=/app/uploads
    volumes:
      - ./excel-processor:/app
      - ./data/uploads:/app/uploads
    networks:
      - default

  # --- 5. FRONTEND (TYPESCRIPT) ---
  frontend-ft:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: gestion_frontend-ft
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules # <-- ASEGÚRATE DE QUE ESTA LÍNEA ESTÉ AQUÍ
      - ./prisma:/app/prisma
    ports:
      - "3000:3000"
    depends_on:
      - backend-ft
    networks:
      - default
      - nexus-network

volumes:
  sqlserver_data:
  mongodb_data:

networks:
  nexus-network:
    external: true