version: '3.8'
name: nexusmanager-prod-devops

services:
  # --- 3. BACKEND API PRINCIPAL (TYPESCRIPT) ---
  backend-pd:
    build: ./backend
    container_name: gestion_backend_ts_prod-devops
    restart: always
    ports:
      - "8000:8000"
    environment:
      - SQL_SERVER_URL=mssql://sa:${SQL_SA_PASSWORD}@sqlserver-pd:1433/gestion_db
      - MONGO_URL=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb-pd:27017/
      - UPLOAD_DIR=/app/uploads
      - PYTHON_SERVICE_URL=http://excel-processor-pd:8001
    volumes:
      - ./data/uploads:/app/uploads
    networks:
      - default
      - nexus-network

  # --- 4. PROCESADOR DE EXCEL (PYTHON) ---
  excel-processor-pd:
    build: ./excel-processor
    container_name: gestion_python_worker_prod-devops
    restart: always
    ports:
      - "8001:8001"
    environment:
      - SQL_SERVER_URL=mssql+pyodbc://sa:${SQL_SA_PASSWORD}@sqlserver-pd:1433/gestion_db?driver=ODBC+Driver+18+for+SQL+Server
      - MONGO_URL=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb-pd:27017/
      - UPLOAD_DIR=/app/uploads
    volumes:
      - ./data/uploads:/app/uploads
    networks:
      - default

  # --- 5. FRONTEND (TYPESCRIPT) ---
  frontend-pd:
    build: ./frontend
    container_name: gestion_frontend_prod-devops
    restart: always
    depends_on:
      - backend-pd
    networks:
      - default
      - nexus-network

networks:
  nexus-network:
    external: true