version: '3.8'
name: nexusmanager-prod

services:
  # --- 1. BASE DE DATOS SQL SERVER ---
  sqlserver-pd:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: gestion_sqlserver
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=KMNnjHMjkkjVFvtv45b34b67bB6bu
      - MSSQL_AGENT_ENABLED=True
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - default

  # --- 2. BASE DE DATOS MONGO DB ---
  mongodb-pd:
    image: mongo:7.0.34-jammy
    container_name: gestion_mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=usuario_mongo
      - MONGO_INITDB_ROOT_PASSWORD=KMNnjHMjkkjVFvtv45b34b67bB6bu
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - default

  # --- 3. BACKEND API PRINCIPAL (TYPESCRIPT) ---
  backend-pd:
    build: ./backend
    container_name: gestion_backend_ts
    restart: always
    ports:
      - "8000:8000"
    environment:
      - SQL_SERVER_URL=mssql://sa:KMNnjHMjkkjVFvtv45b34b67bB6bu@sqlserver-pd:1433/gestion_db
      - MONGO_URL=mongodb://usuario_mongo:KMNnjHMjkkjVFvtv45b34b67bB6bu@mongodb-pd:27017/
      - UPLOAD_DIR=/app/uploads
      - PYTHON_SERVICE_URL=http://excel-processor-pd:8001
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./data/uploads:/app/uploads
    depends_on:
      - sqlserver-pd
      - mongodb-pd
    networks:
      - default
      - nexus-network # <- Para que NPM lo pueda redirigir directamente si expones la API

  # --- 4. PROCESADOR DE EXCEL (PYTHON) ---
  excel-processor-pd:
    build: ./excel-processor
    container_name: gestion_python_worker
    restart: always
    ports:
      - "8001:8001"
    environment:
      - SQL_SERVER_URL=mssql+pyodbc://sa:KMNnjHMjkkjVFvtv45b34b67bB6bu@sqlserver:1433/gestion_db?driver=ODBC+Driver+18+for+SQL+Server
      - MONGO_URL=mongodb://usuario_mongo:KMNnjHMjkkjVFvtv45b34b67bB6bu@mongodb:27017/
      - UPLOAD_DIR=/app/uploads
    volumes:
      - ./excel-processor:/app
      - ./data/uploads:/app/uploads
    depends_on:
      - sqlserver-pd
      - mongodb-pd
    networks:
      - default

  # --- 5. FRONTEND (TYPESCRIPT) ---
  frontend-pd:
    build: ./frontend
    container_name: gestion_frontend
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend-pd
    networks:
      - default
      - nexus-network # El proxy lo buscará aquí

volumes:
  sqlserver_data:
  mongodb_data:

networks:
  nexus-network:
    external: true