name: Despliegue Proyecto B - Desarrollo

on:
  push:
    branches:
      - develop
      - 'feature/*' # Se activa con sus ramas de trabajo

jobs:
  deploy:
    runs-on: [self-hosted, feature-nexus] # <-- ¡GitHub enviará el código solo a la carpeta B!
    defaults:
      run:
        shell: powershell -ExecutionPolicy Bypass -Command Clean-String -Command " . '{0}' "
    steps:
      - name: Descargar codigo actual
        uses: actions/checkout@v4

      - name: Levantar Docker de Desarrollo
        run: |
          docker compose -f docker-compose.feature.yml down
          docker compose -f docker-compose.feature.yml up -d --build
      - name: Levantar Docker de Produccion
        run: |
          docker compose -f docker-compose.prod.yml down
          docker compose -f docker-compose.prod.yml up -d --build

